#!/bin/bash

VAR=0

while getopts "i:(ip)-h(help)-:" opt
do
    case $opt in
        h ) echo -e "Usage: weblog_helper [option] <ADDRESS>\n"; 
            echo -e "Options:\n\n\t"
            echo -e "\t-i --ip\t\tIP ADDRESS or CIDR ADDRESS\n";
            echo -e "\t-h --help\tusage help\n";
            shift;;
        i ) VAR=$2; shift;; 
    esac
done


IPCALC=$(which ipcalc)
REGEX_IPv4='^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
IPCALC_NETWORK=`"$IPCALC" "$VAR" |grep 'Network' |awk '{print $2}'`
IPCALC_ADDRESS=`"$IPCALC" "$VAR" |grep 'Address' | awk '{print $2}'`
FILE=./source.txt

while read line
do
    if [[ "$VAR" =~ $REGEX_IPv4 ]] && [[ "$VAR" == "${VAR%/*}" ]]; then 
        grep $VAR
    else
        [[ "$VAR" =~ $REGEX_IPv4 ]] && network=$IPCALC_NETWORK
        ip=`echo $line |awk '{print $1}'`
        var=`"$IPCALC" "$ip" |grep 'Network' |awk '{print $2}'`
        # if [[ "$network" == $var ]] && [[ "${network%/*}" == "$IPCALC_ADDRESS"  ]];then
        if [[ "$network" == $var ]];then
            echo "$line" | grep "$ip"
        fi
    fi
done < "$FILE"


