#!/bin/bash

VAR=0

while getopts "i:(ip)-h(help)f:(file)-:" opt
do
    case $opt in
        h ) echo "Usage: weblog_helper [option] <ADDRESS> [option] <FILE>";
            echo "Usage: weblog_helper [option] <ADDRESS>";
            echo "";
            echo "Options:"
            echo "    -i --ip        IP ADDRESS or CIDR ADDRESS";
            echo "    -f --file      Input file default: source.txt";
            echo "    -h --help      Usage help";
            exit;
            shift;;
        i ) VAR=$2; shift;;
        f ) FILE=$3;;
    esac
done


IPCALC=$(which ipcalc)
REGEX_IPv4='^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
IPCALC_NETWORK=`"$IPCALC" "$VAR" |grep 'Network' |awk '{print $2}'`
IPCALC_ADDRESS=`"$IPCALC" "$VAR" |grep 'Address' | awk '{print $2}'`
FILE=./source.txt
if [ ! -f $FILE ];then
    FILE=$3
fi

while read line
do
    if [[ "$VAR" =~ $REGEX_IPv4 ]] && [[ "$VAR" == "${VAR%/*}" ]]; then 
        grep -w $VAR
    else
        [[ "$VAR" =~ $REGEX_IPv4 ]] && network=$IPCALC_NETWORK
        ip=`echo $line |awk '{print $1}'`
        var=`"$IPCALC" "$ip" |grep 'Network' |awk '{print $2}'`
        # if [[ "$network" == $var ]] && [[ "${network%/*}" == "$IPCALC_ADDRESS"  ]];then
        if [[ "$network" == $var ]];then
            echo "$line" | grep "$ip"
        fi
    fi
done < "$FILE"


